#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v2
# autospec commit: e661f3a625d7
#
Name     : perl-Sub-Infix
Version  : 0.004
Release  : 3
URL      : https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Sub-Infix-0.004.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TOBYINK/Sub-Infix-0.004.tar.gz
Summary  : 'create a fake infix operator'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Sub-Infix-license = %{version}-%{release}
Requires: perl-Sub-Infix-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::Fatal)
BuildRequires : perl(Try::Tiny)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Sub::Infix - create a fake infix operator
SYNOPSIS
use Sub::Infix;

# Operator needs to be defined (or imported) at compile time.
BEGIN { *plus = infix { $_[0] + $_[1] } };

my $five = 2 |plus| 3;

%package dev
Summary: dev components for the perl-Sub-Infix package.
Group: Development
Provides: perl-Sub-Infix-devel = %{version}-%{release}
Requires: perl-Sub-Infix = %{version}-%{release}

%description dev
dev components for the perl-Sub-Infix package.


%package license
Summary: license components for the perl-Sub-Infix package.
Group: Default

%description license
license components for the perl-Sub-Infix package.


%package perl
Summary: perl components for the perl-Sub-Infix package.
Group: Default
Requires: perl-Sub-Infix = %{version}-%{release}

%description perl
perl components for the perl-Sub-Infix package.


%prep
%setup -q -n Sub-Infix-0.004
cd %{_builddir}/Sub-Infix-0.004

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Sub-Infix
cp %{_builddir}/Sub-Infix-%{version}/COPYRIGHT %{buildroot}/usr/share/package-licenses/perl-Sub-Infix/ffd490b89a71ab941f76c946b245af0002987498 || :
cp %{_builddir}/Sub-Infix-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Sub-Infix/34f5e12514b91055de4b164a1f2327ef5c30ba53 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Sub::Infix.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Sub-Infix/34f5e12514b91055de4b164a1f2327ef5c30ba53
/usr/share/package-licenses/perl-Sub-Infix/ffd490b89a71ab941f76c946b245af0002987498

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
